#include <stddef.h>
#include "definicoes.h"
#include "utilidades.h"
#include "../Lista/lista.h"
#include "../Fila/fila.h"
#include "../Pilha/pilha.h"
#include "../Grafo/grafoLA.h"
#include "../Vetor/vetor.h"
#include "../String/stringVar.h"
